USE [master]
GO

/****** Object:  Database [GTI]    Script Date: 25/07/2022 13:59:26 ******/
CREATE DATABASE [GTI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GTI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GTI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GTI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GTI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GTI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GTI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GTI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GTI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GTI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GTI] SET ARITHABORT OFF 
GO

ALTER DATABASE [GTI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GTI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GTI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GTI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GTI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GTI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GTI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GTI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GTI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GTI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GTI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GTI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GTI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GTI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GTI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GTI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GTI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GTI] SET RECOVERY FULL 
GO

ALTER DATABASE [GTI] SET  MULTI_USER 
GO

ALTER DATABASE [GTI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GTI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GTI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GTI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GTI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GTI] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GTI] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GTI] SET  READ_WRITE 
GO

